# Created by: Jiri Kubicek <jiri.kubicek@kraxnet.cz>
# $FreeBSD$

PORTNAME=	sensu
PORTVERSION=	0.9.13
CATEGORIES=	net-mgmt rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Sensu is a monitoring framework

SENSU_SERVER_CONFIG_FILE?=	${PREFIX}/etc/sensu.conf
SENSU_SERVER_CONFIG_DIR?=	${PREFIX}/etc/sensu/conf.d
SENSU_SERVER_LOG_FILE?=		/var/log/sensu/server.log
SUB_LIST+=	SENSU_SERVER_CONFIG_FILE=${SENSU_SERVER_CONFIG_FILE} SENSU_SERVER_CONFIG_DIR=${SENSU_SERVER_CONFIG_DIR} SENSU_SERVER_LOG_FILE=${SENSU_SERVER_LOG_FILE}

SENSU_CLIENT_CONFIG_FILE?=	${PREFIX}/etc/sensu_client.conf
SENSU_CLIENT_CONFIG_DIR?=	${SENSU_SERVER_CONFIG_DIR}
SENSU_CLIENT_LOG_FILE?=		/var/log/sensu/client.log
SUB_LIST+=	SENSU_CLIENT_CONFIG_FILE=${SENSU_CLIENT_CONFIG_FILE} SENSU_CLIENT_CONFIG_DIR=${SENSU_CLIENT_CONFIG_DIR} SENSU_CLIENT_LOG_FILE=${SENSU_CLIENT_LOG_FILE}
SUB_LIST+=	SENSU_API_CONFIG_FILE=${SENSU_API_CONFIG_FILE} SENSU_API_CONFIG_DIR=${SENSU_API_CONFIG_DIR} SENSU_API_LOG_FILE=${SENSU_API_LOG_FILE}

SENSU_API_CONFIG_FILE?=		${SENSU_SERVER_CONFIG_FILE}
SENSU_API_CONFIG_DIR?=		${SENSU_SERVER_CONFIG_DIR}
SENSU_API_LOG_FILE?=		/var/log/sensu/api.log

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
SUB_LIST+=	RUBY=${RUBY}

USE_RC_SUBR=	sensu_server sensu_client sensu_api

.include <bsd.port.mk>